@PujcovadloServer_HostAddress = http://localhost:5046/api
@PujcovadloServer_Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJqdGkiOiI1ZGM3M2E4ZC03NzcwLTQ2NzMtYjk4Yy1kMTYwMTRkMzFiMWUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiVXNlciIsIlRlbmFudCIsIk93bmVyIl0sImV4cCI6MTcwNjY4OTIyNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDQ2IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDQ2In0.RpmVtSozIO0cTFXSnJprUvMC6Ocdmrq83VekpVBimw4

GET {{PujcovadloServer_HostAddress}}/items/
Accept: application/json

###
GET {{PujcovadloServer_HostAddress}}/my-items/
Accept: application/json
Authorization: Bearer {{PujcovadloServer_Token}}

###
GET {{PujcovadloServer_HostAddress}}/items/?Page=1&PageSize=3&Sortby=Id&SortOrder=True&status=3
Accept: application/json

###
GET {{PujcovadloServer_HostAddress}}/items/1
Accept: application/json
Authorization: Bearer {{PujcovadloServer_Token}}

###
GET {{PujcovadloServer_HostAddress}}/items/1/categories
Accept: application/json

###
GET {{PujcovadloServer_HostAddress}}/item-categories/1/items
Accept: application/json

###

POST {{PujcovadloServer_HostAddress}}/items/
Content-Type: application/json
Authorization: Bearer {{PujcovadloServer_Token}}

{
  "name": "Test item",
  "description": "Popis testovacího itemu.",
  "status": 3,
  "parameters": "velikost 10",
  "pricePerDay": 100,
  "updatedAt": "2018-01-01T00:00:00"
}

###
PUT {{PujcovadloServer_HostAddress}}/items/1
Content-Type: application/json
Authorization: Bearer {{PujcovadloServer_Token}}

{
  "id": 1,
  "name": "Úprava testovací položky 1",
  "description": "Popis testovacího itemu.",
  "status": 2,
  "parameters": "velikost 12",
  "pricePerDay": 120
}

###
DELETE {{PujcovadloServer_HostAddress}}/items/1

###
GET {{PujcovadloServer_HostAddress}}/item-categories
Accept: application/json
Authorization: Bearer {{PujcovadloServer_Token}}

###
POST {{PujcovadloServer_HostAddress}}/item-categories
Content-Type: application/json
Authorization: Bearer {{PujcovadloServer_Token}}

{
  "name": "Testovací kategorie",
  "description": "Popis testovací kategorie."
}

###
POST {{PujcovadloServer_HostAddress}}/Authenticate/login
Content-Type: application/json

{
  "username": "admin",
  "password": "MojekrasneHeslo_123"
}

###
POST {{PujcovadloServer_HostAddress}}/Authenticate/register
Content-Type: application/json

{
  "firstName": "Jaroslav",
  "lastName": "Fikar",
  "username": "admin",
  "password": "MojekrasneHeslo_123",
  "passwordConfirmation": "MojekrasneHeslo_123",
  "email": "jara.fikar@seznam.cz"
}

###