@PujcovadloServer_HostAddress = http://localhost:5046

GET {{PujcovadloServer_HostAddress}}/api/items/
Accept: application/json

###
GET {{PujcovadloServer_HostAddress}}/api/items/?Page=1&PageSize=3&Sortby=Id&SortOrder=True&status=3
Accept: application/json

###
GET {{PujcovadloServer_HostAddress}}/api/items/1
Accept: application/json

###
GET {{PujcovadloServer_HostAddress}}/api/items/1/categories
Accept: application/json

###
GET {{PujcovadloServer_HostAddress}}/api/item-categories/1/items
Accept: application/json

###

POST {{PujcovadloServer_HostAddress}}/api/items/
Content-Type: application/json

{
  "name": "Test item",
  "description": "Popis testovacího itemu.",
  "status": 3,
  "parameters": "velikost 10",
  "pricePerDay": 100,
  "updatedAt": "2018-01-01T00:00:00"
}

###
PUT {{PujcovadloServer_HostAddress}}/api/items/1
Content-Type: application/json

{
  "id": 1,
  "name": "Úprava testovací položky 16",
  "description": "Popis testovacího itemu.",
  "status": 2,
  "parameters": "velikost 12",
  "pricePerDay": 120
}

###
DELETE {{PujcovadloServer_HostAddress}}/api/items/1

###
POST {{PujcovadloServer_HostAddress}}/api/item-categories
Content-Type: application/json

{
  "name": "Testovací kategorie",
  "description": "Popis testovací kategorie."
}